import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
   return (
     <>
       <div
         style={{ width: "100vh", justifyContent: "center", display: "flext" }}
       >
         <div style={{ width: "400px", border: "1px solid black" }}>
           <input type="text" name="" placeholder="email" id="" />
           <input type="text" name="" placeholder="password" id="" />
           <button>submit</button>
         </div>
       </div>
     </>
   );
}
